###################################################################################################
#                        Welcome to the Testbed Project's source of truth!                         #
#                                                                                                 #
# Why are we doing this?:                                                                         #
#   As our project grows, it gets hard to keep track of the values on everyone's subsystems as    #
#   they get more and more complicated. Consolidating all of our important design parameters,     #
#   inputs and outputs in the same file helps reduce miscommunications and ensures everyone is in #
#   the same page.                                                                                #
# What the hell is a YAML?:                                                                       #
#   YAML is a type of files that allows people to write data in a way that is readable to both a  #
#   person AND a computer. As opposed to other filetypes like JSON and XML, the syntax is pretty  #
#   nice and readable and will thus make a good reference for programmers and non-programmers in  #
#   the team.                                                                                     #
# (video explaining how to use a YAML) https://www.youtube.com/watch?v=BEki_rsWu4E                #
#                                                                                                 #
# Basic rules:                                                                                    #
#   1. Be clear with naming, limit acronym usage on any parameters you add                        #
#   2. Write the units in a comment using parenthesis and maintain unit system consistency        #
#   3. Write your name next to any parameters you own, notify owners of inputs before             #
#      changing them                                                                              #
#   4. Do not change OUTPUTS manually, only code should do this!!!                                #
#   5. No slop, only throw a value here if it actually is useful information. EX: things like     #
#      shaft speed, design propellant temps... Not things like super specific shaft dimensions or #
#      random off-design conditions                                                               #
#   6. Check if the value is already there before adding it                                       #
#                                                                                                 #
# If you have any questions about how to use this document, reach out to Dominik Sloup            #
# dsloup@purdue.edu                                                                               #
#                                                                                                 #
###################################################################################################

######################################
###### MAELSTROM ENGINE INPUTS #######
######################################

thrust: 500 # (lbf) Dominik Sloup
of_ratio: 1 # (N/A) Dominik Sloup
chamber_pressure: 500 # (psi) Dominik Sloup
exhaust_pressure: 14.7 # (psi) Dominik Sloup
cstar_eff: 0.7 # (N/A) Dominik Sloup

gox_stiffness: 1.2  # (N/A) Dominik Sloup
gox_orifice_number: 24 # (N/A) Dominik Sloup

rp_stiffness: 0.28 # (N/A) Dominik Sloup
rp_orifice_number: 24 # (N/A) Dominik Sloup

######################################
###### MAELSTROM ENGINE OUTPUTS ######
######################################

# Maelstrom Chamber geometry

throat_diameter: 0.95 # (in) Dominik Sloup
exit_diameter: 2 # (in) Dominik Sloup

# Maelstrom Impinging Jet Injector parameters

rp_tube_inner_dia: 0.4  # (in) Dominik Sloup 
gox_tube_inner_dia: 0.65  # (in) Dominik Sloup

rp_design_mdot: 1.344 # (lb/s) Dominik Sloup
rp_feed_pressure: 640.0 # (psi) Dominik 
rp_line_velocity: 30.45  # (ft/s) Dominik Sloup
n2_SCFM: 1108.42 # (ft^3/min) Dominik Sloup

gox_design_mdot: 1.344 # (lb/s) Dominik Sloup
gox_feed_pressure: 1100.0 # (psi) Dominik Sloup
gox_line_velocity: 89.66  # (ft/s) Dominik Sloup
gox_SCFM: 970.05  # (ft^3/min) Dominik Sloup