###################################################################################################
#                        Welcome to the Testbed Project's source of truth!                         #
#                                                                                                 #
# Why are we doing this?:                                                                         #
#   As our project grows, it gets hard to keep track of the values on everyone's subsystems as    #
#   they get more and more complicated. Consolidating all of our important design parameters,     #
#   inputs and outputs in the same file helps reduce miscommunications and ensures everyone is in #
#   the same page.                                                                                #
# What the hell is a YAML?:                                                                       #
#   YAML is a type of files that allows people to write data in a way that is readable to both a  #
#   person AND a computer. As opposed to other filetypes like JSON and XML, the syntax is pretty  #
#   nice and readable and will thus make a good reference for programmers and non-programmers in  #
#   the team.                                                                                     #
# (video explaining how to use a YAML) https://www.youtube.com/watch?v=BEki_rsWu4E                #
#                                                                                                 #
# Basic rules:                                                                                    #
#   1. Be clear with naming, limit acronym usage on any parameters you add                        #
#   2. Write the units in a comment using parenthesis and maintain unit system consistency        #
#   3. Write your name next to any parameters you own, notify owners of inputs before             #
#      changing them                                                                              #
#   4. Do not change OUTPUTS manually, only code should do this!!!                                #
#   5. No slop, only throw a value here if it actually is useful information. EX: things like     #
#      shaft speed, design propellant temps... Not things like super specific shaft dimensions or #
#      random off-design conditions                                                               #
#   6. Check if the value is already there before adding it                                       #
#                                                                                                 #
# If you have any questions about how to use this document, reach out to Dominik Sloup            #
# dsloup@purdue.edu                                                                               #
#                                                                                                 #
###################################################################################################


######################################
###### MAELSTROM ENGINE DESIGN #######
######################################

# Chamber performance (INPUTS)

thrust: 500 # (lbf) Dominik Sloup
chamber_pressure: 500 # (psi) Dominik Sloup

# Chamber geometry

throat_diameter: 0.95 # (in) Dominik Sloup

# GOX/RP-1 Injector parameters (INPUTS)

of_ratio: 1 # (N/A) Dominik Sloup
gox_stiffness: 1.4  # (N/A) Dominik Sloup
rp_stiffness: 0.5  # (N/A) Dominik Sloup

rp_tube_inner_dia: 0.4  # (in) Dominik Sloup 
gox_tube_inner_dia: 0.65  # (in) Dominik Sloup

# GOX/RP-1 Injector parameters (OUTPUTS)

rp_design_mdot: 1.344 # (lb/s) Dominik Sloup
gox_design_mdot: 1.344 # (lb/s) Dominik Sloup

gox_feed_pressure: 1200.0 # (psi) Dominik Sloup
rp_feed_pressure: 750.0 # (psi) Dominik Sloup

gox_line_velocity: 81.93 # (ft/s) Dominik Sloup
rp_line_velocity: 30.45 # (ft/s) Dominik Sloup

# Swirl injector design (OUTPUTS)

element_number: 6

kero_inlet_number: 3 # (N/A) Dominik Sloup
kero_total_injection_area: null # (in^2) Dominik Sloup
kero_inlet_diameter: null # (in) Dominik Sloup

lox_inlet_number: 3 # (N/A) Dominik Sloup
lox_total_injection_area: null # (in^2) Dominik Sloup
lox_inlet_diameter: null # (in) Dominik Sloup