###################################################################################################
#                        Welcome to the Testbed Project's source of truth!                         #
#                                                                                                 #
# Why are we doing this?:                                                                         #
#   As our project grows, it gets hard to keep track of the values on everyone's subsystems as    #
#   they get more and more complicated. Consolidating all of our important design parameters,     #
#   inputs and outputs in the same file helps reduce miscommunications and ensures everyone is in #
#   the same page.                                                                                #
# What the hell is a YAML?:                                                                       #
#   YAML is a type of files that allows people to write data in a way that is readable to both a  #
#   person AND a computer. As opposed to other filetypes like JSON and XML, the syntax is pretty  #
#   nice and readable and will thus make a good reference for programmers and non-programmers in  #
#   the team.                                                                                     #
# (video explaining how to use a YAML) https://www.youtube.com/watch?v=BEki_rsWu4E                #
#                                                                                                 #
# Basic rules:                                                                                    #
#   1. Be clear with naming, limit acronym usage on any parameters you add                        #
#   2. Write the units in a comment using parenthesis and maintain unit system consistency        #
#   3. Write your name next to any parameters you own, notify owners of inputs before             #
#      changing them                                                                              #
#   4. Do not change OUTPUTS manually, only code should do this!!!                                #
#   5. No slop, only throw a value here if it actually is useful information. EX: things like     #
#      shaft speed, design propellant temps... Not things like super specific shaft dimensions or #
#      random off-design conditions                                                               #
#   6. Check if the value is already there before adding it                                       #
#                                                                                                 #
# If you have any questions about how to use this document, reach out to Dominik Sloup            #
# dsloup@purdue.edu                                                                               #
#                                                                                                 #
###################################################################################################

######################################
###### MAELSTROM ENGINE INPUTS #######
######################################

thrust: 400 # (lbf) Dominik Sloup
of_ratio: 1 # (N/A) Dominik Sloup
chamber_pressure: 250 # (psi) Dominik Sloup
exhaust_pressure: 14.7 # (psi) Dominik Sloup
regen_pressure_drop: 100 # (psi) James Nida
cstar_eff: 0.7 # (N/A) Dominik Sloup
isp_eff: 1 # (N/A) Dominik Sloup
Lstar: 55 # (in) Dominik Sloup

chamber_diameter: 3.4   # (in)  Dominik Sloup
converging_angle: 45    # (deg) Dominik Sloup
diverging_angle: 13.5   # (deg) Dominik Sloup
converging_fillet: 0.5  # (in)  Dominik Sloup
throat_fillet: 0.4     # (in)   Dominik Sloup

gox_stiffness: 1.2  # (N/A) Dominik Sloup
gox_orifice_number: 24 # (N/A) Dominik Sloup
gox_discharge_coeff: 0.8 # (N/A) Dominik Sloup
gox_tube_inner_dia: 0.65 # (in) Dominik Sloup

rp_stiffness: 0.28 # (N/A) Dominik Sloup
rp_orifice_number: 24 # (N/A) Dominik Sloup
rp_discharge_coeff: 0.8 # (N/A) Dominik Sloup
rp_tube_inner_dia: 0.4 # (in) Dominik Sloup

######################################
###### MAELSTROM ENGINE OUTPUTS ######
######################################

# Expected performance parameters

cstar: 965  # (m/s) Dominik Sloup
isp: 143 # (s) Dominik Sloup

# Maelstrom Chamber geometry

throat_diameter: 1.182 # (in) Dominik Sloup
exit_diameter: 2.041 # (in) Dominik Sloup
total_length: 6.0  # (in)  Dominik Sloup
chamber_volume: 60.4 # (in^3) Dominik Sloup

# Maelstrom Impinging Jet Injector parameters

rp_design_mdot: 1.393 # (lb/s) Dominik Sloup
rp_orifice_dia: 0.048 # (in) Dominik Sloup
rp_feed_pressure: 420 # (psi) Dominik Sloup
rp_line_velocity: 31.57 # (ft/s) Dominik Sloup
n2_SCFM: 1149.14 # (ft^3/min) Dominik Sloup

gox_design_mdot: 1.393 # (lb/s) Dominik Sloup
gox_orifice_dia: 0.083 # (in) Dominik Sloup
gox_feed_pressure: 550  # (psi) Dominik Sloup
gox_line_velocity: 189.73 # (ft/s) Dominik Sloup
gox_SCFM: 1005.68 # (ft^3/min) Dominik Sloup
